
import type { CardData } from './types';

export const INITIAL_HP = 20;
export const HAND_SIZE = 5;
export const DECK_SIZE = 20;
export const MAX_DUPLICATES = 4;
export const INITIAL_UNLOCKED_CARDS: number[] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17, 19, 20, 21, 22, 23, 24];

// 管理者のメールアドレスリスト。ここにメールアドレスを追加すると、そのユーザーだけがGameMasterボタンを見ることができます。
export const ADMIN_EMAILS: string[] = [];

export const GAMEMASTER_PASSWORD = '215124';

// This catalog contains all possible card DEFINITIONS.
export const CARD_DEFINITIONS: CardData[] = ([
  // --- Base Cards (Definition IDs 0-9) ---
  {
    name: "エレガントな貴族",
    attack: 7,
    defense: 7,
    image: "1.jpeg",
    description: "非の打ち所がないスタイルを持つ、バランスの取れた戦士。",
    effect: 'NONE',
    attribute: 'passion',
    level: 1,
    unlocks: 10,
    baseDefinitionId: 0,
  },
  {
    name: "輝く花嫁",
    attack: 2,
    defense: 6,
    image: "2.jpeg",
    description: "場に出した時、その誓いがあなたのHPを3回復する。",
    effect: 'HEAL_PLAYER',
    effectValue: 3,
    attribute: 'harmony',
    level: 1,
    unlocks: 11,
    baseDefinitionId: 1,
  },
  {
    name: "ステージアイドル",
    attack: 5,
    defense: 5,
    image: "3.jpeg",
    description: "ステージ上で輝く、万能なパフォーマー。",
    effect: 'NONE',
    attribute: 'harmony',
    level: 1,
    unlocks: 12,
    baseDefinitionId: 2,
  },
  {
    name: "バレーのエース",
    attack: 10,
    defense: 1,
    image: "4.jpeg",
    description: "ブロックすることがほぼ不可能な、全力のスパイク。",
    effect: 'NONE',
    attribute: 'passion',
    baseDefinitionId: 3,
  },
  {
    name: "怜悧な探偵",
    attack: 4,
    defense: 4,
    image: "5.jpeg",
    description: "場に出した時、その鋭い知性がカードを1枚引かせる。",
    effect: 'DRAW_CARD',
    effectValue: 1,
    attribute: 'calm',
    baseDefinitionId: 4,
  },
  {
    name: "陽気なマスコット",
    attack: 3,
    defense: 3,
    image: "6.jpeg",
    description: "場に出した時、その元気な応援がHPを2回復する。",
    effect: 'HEAL_PLAYER',
    effectValue: 2,
    attribute: 'harmony',
    baseDefinitionId: 5,
  },
  {
    name: "屈強なチャンピオン",
    attack: 9,
    defense: 4,
    image: "7.jpeg",
    description: "厳しいトレーニングで磨かれた、圧倒的なパワー。",
    effect: 'NONE',
    attribute: 'passion',
    baseDefinitionId: 6,
  },
  {
    name: "サッカーのストライカー",
    attack: 7,
    defense: 2,
    image: "8.jpeg",
    description: "場に出した時、2ダメージのシュートを放つ。",
    effect: 'DIRECT_DAMAGE',
    effectValue: 2,
    attribute: 'passion',
    baseDefinitionId: 7,
  },
  {
    name: "忠実な執事",
    attack: 1,
    defense: 11,
    image: "9.jpeg",
    description: "あらゆる動きを先読みする完璧な防御。",
    effect: 'NONE',
    attribute: 'calm',
    baseDefinitionId: 8,
  },
  {
    name: "マイクドロップ・ラッパー",
    attack: 4,
    defense: 3,
    image: "10.jpeg",
    description: "場に出した時、そのリリックが3ダメージを与える。",
    effect: 'DIRECT_DAMAGE',
    effectValue: 3,
    attribute: 'calm',
    baseDefinitionId: 9,
  },
  // --- Leveled Cards (Definition IDs 10-15) ---
  {
    name: "至高の貴族",
    attack: 8,
    defense: 8,
    image: "12.jpeg",
    description: "更に高められた品格。場に出た時、1ダメージを与える。",
    effect: 'DIRECT_DAMAGE',
    effectValue: 1,
    attribute: 'passion',
    level: 2,
    unlocks: 13,
    baseDefinitionId: 0,
  },
  {
    name: "永遠の花嫁",
    attack: 3,
    defense: 8,
    image: "14.jpeg",
    description: "永遠の愛を誓い、HPを5回復する。",
    effect: 'HEAL_PLAYER',
    effectValue: 5,
    attribute: 'harmony',
    level: 2,
    unlocks: 14,
    baseDefinitionId: 1,
  },
  {
    name: "センターアイドル",
    attack: 6,
    defense: 6,
    image: "16.jpeg",
    description: "ファンの声援に応え、カードを1枚引く。",
    effect: 'DRAW_CARD',
    effectValue: 1,
    attribute: 'harmony',
    level: 2,
    unlocks: 15,
    baseDefinitionId: 2,
  },
  {
    name: "気高き皇帝",
    attack: 10,
    defense: 10,
    image: "13.jpeg",
    description: "絶対的な風格。場に出た時、3ダメージを与える。",
    effect: 'DIRECT_DAMAGE',
    effectValue: 3,
    attribute: 'passion',
    level: 3,
    baseDefinitionId: 0,
  },
  {
    name: "女神の花嫁",
    attack: 5,
    defense: 10,
    image: "15.jpeg",
    description: "女神の祝福がHPを8回復させる。",
    effect: 'HEAL_PLAYER',
    effectValue: 8,
    attribute: 'harmony',
    level: 3,
    baseDefinitionId: 1,
  },
  {
    name: "伝説のアイドル",
    attack: 7,
    defense: 7,
    image: "17.jpeg",
    description: "伝説のステージ。カードを2枚引かせる。",
    effect: 'DRAW_CARD',
    effectValue: 2,
    attribute: 'harmony',
    level: 3,
    baseDefinitionId: 2,
  },
  // --- Special Effect Cards (Definition IDs 16-24) ---
  {
    name: "怪盗ブラック・ルナ",
    attack: 5,
    defense: 3,
    image: "1.jpeg",
    description: "相手の手札を1枚奪い去る。",
    effect: 'DISCARD_HAND',
    effectValue: 1,
    attribute: 'calm',
    baseDefinitionId: 16,
  },
  {
    name: "禁忌の魔術師",
    attack: 4,
    defense: 4,
    image: "5.jpeg",
    description: "相手の手札を1枚捨てさせる。",
    effect: 'DISCARD_HAND',
    effectValue: 1,
    attribute: 'passion',
    baseDefinitionId: 17,
  },
  {
    name: "運命の裁定者",
    attack: 6,
    defense: 2,
    image: "12.jpeg",
    description: "相手の手札を2枚破棄させる。",
    effect: 'DISCARD_HAND',
    effectValue: 2,
    attribute: 'calm',
    level: 2,
    baseDefinitionId: 19,
  },
  {
    name: "紅蓮の吸血鬼",
    attack: 6,
    defense: 4,
    image: "7.jpeg",
    description: "ライフドレイン！相手から2HPを吸収する。",
    effect: 'LIFE_DRAIN',
    effectValue: 2,
    attribute: 'passion',
    baseDefinitionId: 20,
  },
  {
    name: "聖なる守護者",
    attack: 3,
    defense: 6,
    image: "9.jpeg",
    description: "シールド！発動時、防御力を+4する。",
    effect: 'SHIELD',
    effectValue: 4,
    attribute: 'harmony',
    baseDefinitionId: 21,
  },
  {
    name: "虚飾の鏡",
    attack: 2,
    defense: 10,
    image: "5.jpeg",
    description: "反射！ダメージを受けた時、相手に3ダメージ返す。",
    effect: 'REFLECT',
    effectValue: 3,
    attribute: 'calm',
    baseDefinitionId: 22,
  },
  {
    name: "狂乱の戦士",
    attack: 5,
    defense: 3,
    image: "13.jpeg",
    description: "バーサク！自分のHPが10以下なら、攻撃力が+5される。",
    effect: 'BERSERK',
    effectValue: 5,
    attribute: 'passion',
    baseDefinitionId: 23,
  },
  {
    name: "漆黒の騎士",
    attack: 12,
    defense: 0,
    image: "1.jpeg",
    description: "反動！絶大な攻撃力を持つが、自分も2ダメージ受ける。",
    effect: 'RECOIL',
    effectValue: 2,
    attribute: 'calm',
    baseDefinitionId: 24,
  }
] as Omit<CardData, 'id' | 'definitionId'>[]).map((card, index) => ({ ...card, definitionId: index, id: index }));

export const CardCatalogById = CARD_DEFINITIONS.reduce((acc, card) => {
  acc[card.definitionId] = card;
  return acc;
}, {} as Record<number, CardData>);
